SET SQL DIALECT 3;

SET NAMES UTF8;

CREATE DATABASE 'LOCALHOST:\workspace\docs_v1.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE REQUEST (
    ID_REQ          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    RECEIVE_DATE    DATE,
    FROM_SMO        INTEGER,
    REQUEST_NUMBER  VARCHAR(15),
    DUE_DATE        DATE,
    RECEIVED_FILES  BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    SEND            SMALLINT,
    DAYS_LEFT       COMPUTED BY (request.DUE_DATE - current_date),
    FILE_TYPE       VARCHAR(4)
);

CREATE TABLE SMO (
    SMO_ID    SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    SMO_NAME  VARCHAR(25)
);

INSERT INTO SMO (SMO_ID, SMO_NAME) VALUES (1, 'Ингосстрах-М');
INSERT INTO SMO (SMO_ID, SMO_NAME) VALUES (2, 'Альфастрахование-ОМС');
INSERT INTO SMO (SMO_ID, SMO_NAME) VALUES (3, 'РЕСО-Мед');
INSERT INTO SMO (SMO_ID, SMO_NAME) VALUES (4, 'АстраМед-МС');
INSERT INTO SMO (SMO_ID, SMO_NAME) VALUES (5, 'СОГАЗ-Мед');
INSERT INTO SMO (SMO_ID, SMO_NAME) VALUES (6, 'ТФОМС ЧО');


COMMIT WORK;

INSERT INTO REQUEST (ID_REQ, RECEIVE_DATE, FROM_SMO, REQUEST_NUMBER, DUE_DATE, SEND, FILE_TYPE) VALUES (2, NULL, 2, '74039100176', NULL, 1, 'docx');

COMMIT WORK;



/******************************************************************************/
/***                        Autoincrement generators                        ***/
/******************************************************************************/

ALTER TABLE REQUEST ALTER ID_REQ RESTART WITH 534;
ALTER TABLE SMO ALTER SMO_ID RESTART WITH 6;




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE REQUEST ADD CONSTRAINT PK_REQUEST PRIMARY KEY (ID_REQ);
ALTER TABLE SMO ADD CONSTRAINT PK_SMO PRIMARY KEY (SMO_ID);


/******************************************************************************/
/***                              Foreign keys                              ***/
/******************************************************************************/

ALTER TABLE REQUEST ADD CONSTRAINT FK_REQUEST_SMO FOREIGN KEY (FROM_SMO) REFERENCES SMO (SMO_ID) ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN REQUEST.RECEIVE_DATE IS
'Дата получения запроса';

COMMENT ON COLUMN REQUEST.FROM_SMO IS
'От кого';

COMMENT ON COLUMN REQUEST.REQUEST_NUMBER IS
'Номер запроса';

COMMENT ON COLUMN REQUEST.DUE_DATE IS
'До какого числа нужен ответ';

COMMENT ON COLUMN REQUEST.RECEIVED_FILES IS
'Полученные файлы';

COMMENT ON COLUMN REQUEST.SEND IS
'Отметка об отправке документации';

